### ISSUE TITLE
Domain Name?

### ISSUE THREAD

**Issue by jfelchner** [embercasts/embercasts#14]
@ebryn what's the state on the domain name?  If you're going to let it expire, I'd be interested in picking it up.  I was going to try to do a few screencasts on my experience with getting Ember going on a Rails app we're working on.  I'd love to have embercasts.com but I didn't know if you'd be willing to part with it.

No big deal, just lemme know either way.  Thanks!

**Comment by jfelchner** [comment]
@ebryn I just followed you on Twitter if you'd rather DM me.

**Comment by ebryn** [comment]
Oops, missed the renewal emails. Thanks for letting me know, but I plan on keeping the site going.
