### ISSUE TITLE
Not able to see the videoes in Latest Chrome Ubuntu Linux

### ISSUE THREAD

**Issue by devilankur18** [embercasts/embercasts#4]

**Comment by ebryn** [comment]
Can you try http://staging.embercasts.com and see if that works?
- Erik

Sent from my iPhone

On May 14, 2013, at 8:05 PM, Ankur Agarwal notifications@github.com wrote:

—
Reply to this email directly or view it on
GitHubhttps://github.com/embercasts/embercasts/issues/4
.

**Comment by devilankur18** [comment]
Yeah this is working.

**Comment by ebryn** [comment]
Thanks!
